//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Complain
    {
        public int Id { get; set; }

        
        public string UserName { get; set; }

        [Required(ErrorMessage = "This Field is Required.")]
        public string complain1 { get; set; }

        
        public string Complainer { get; set; }
    }
}
