//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialHub.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.Friends = new HashSet<Friend>();
            this.Posts = new HashSet<Post>();
            this.Friends1 = new HashSet<Friend>();
            this.Comments = new HashSet<Comment>();
        }







        [Required(ErrorMessage = "This Field is Required.")]
        [MinLength(5, ErrorMessage = "User Nmae Length must be 5 to 20 Letters.")]
        [MaxLength(20, ErrorMessage = "User Nmae Length must be 5 to 20 Letters.")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "This Field is Required.")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "This Field is Required.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "This Field is Required.")]
        public string PhoneNo { get; set; }

        [Required(ErrorMessage = "This Field is Required.")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "This Field is Required.")]
        public string SecretQuestion { get; set; }

        [Required(ErrorMessage = "This Field is Required.")]
        public string SecretAnswer { get; set; }

        [MinLength(5, ErrorMessage = "Password Length must be 5 to 20.")]
        [MaxLength(20, ErrorMessage = "Password Length must be 5 to 20.")]
        [Required(ErrorMessage = "This Field is Required.")]
        public string Password { get; set; }
        public virtual ICollection<Friend> Friends { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Friend> Friends1 { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
